name: Docker Image Build & Push
description: Build and push a Docker image for the application inside the specified path
inputs:
  build-id:
    description: The build id where this asset belongs to
    required: true
  path:
    description: The path where the Dockerfile file is located
    required: false
    default: .
  name:
    description: Asset name, by default 'main'
    required: false
    default: main
runs:
  using: composite
  steps:
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build Docker image
      id: docker-build-image
      shell: bash
      run: docker build -t docker-image -f ${{ inputs.path }}/Dockerfile .
    - name: Create asset for build
      id: create-asset
      uses: nullplatform/github-action-asset@v1
      with:
        action: create
        build-id: ${{ inputs.build-id }}
        type: docker-image
        name: ${{ inputs.name }}
    - name: Push Docker image
      id: docker-push-image
      shell: bash
      env:
        IMAGE_TAG: ${{ fromJson(steps.create-asset.outputs.targets)[0].url }}
      run: |
        docker tag docker-image:latest $IMAGE_TAG
        docker push $IMAGE_TAG
