name: Lambda ZIP Build & Push
description: Build and push a ZIP file for the application inside the specified path
inputs:
  build-id:
    description: The build id where this asset belongs to
    required: true
  path:
    description: The path where the ZIP file must be generated
    required: false
    default: .
  name:
    description: Asset name, by default 'main'
    required: false
    default: main
runs:
  using: composite
  steps:
    - name: Build asset file
      id: makefile-build-file
      shell: bash
      env:
        WORKING_DIRECTORY: ${{ inputs.path }}
        ASSET_OUTPUT_DIRECTORY: ${{ inputs.path }}/build
        ASSET_FILE: ${{ inputs.name }}.zip
      run: |
        make build WORKING_DIRECTORY=$WORKING_DIRECTORY ASSET_OUTPUT_DIRECTORY=$ASSET_OUTPUT_DIRECTORY
        cd $ASSET_OUTPUT_DIRECTORY
        zip -r $ASSET_FILE .
    - name: Create asset for build
      id: create-asset
      uses: nullplatform/github-action-asset@v1
      with:
        action: create
        build-id: ${{ inputs.build-id }}
        type: lambda
        name: ${{ inputs.name }}
    - name: Push asset file
      id: s3-push-file
      shell: bash
      env:
        ASSET_FILE: ${{ inputs.path }}/build/${{ inputs.name }}.zip
        TARGET_URL: ${{ fromJson(steps.create-asset.outputs.targets)[0].url }}
      run: aws s3 cp $ASSET_FILE ${{ env.TARGET_URL }}
